On Ubuntu 26.04 arm64, libvirt-qemu user and group get created in the apt install transaction after the libvirtd.service started.
Addressing
error: Failed to start domain 'vm1.example.com'
error: /usr/lib/qemu/qemu-bridge-helper --use-vnet --br=virbr0 --fd=31: failed to communicate with bridge helper: stderr=failed to get mtu of bridge `virbr0': No such device

due to

Jun 12 15:26:19 runnervm48rkm systemd[1]: Starting libvirtd.service - libvirt legacy monolithic daemon...
Jun 12 15:26:19 runnervm48rkm systemd[1]: Started libvirtd.service - libvirt legacy monolithic daemon.
Jun 12 15:26:19 runnervm48rkm libvirtd[7562]: libvirt version: 12.0.0, package: 12.0.0-1ubuntu5 (Ubuntu)
Jun 12 15:26:19 runnervm48rkm libvirtd[7562]: hostname: runnervm48rkm
Jun 12 15:26:19 runnervm48rkm libvirtd[7562]: invalid argument: Failed to parse user 'libvirt-qemu'
Jun 12 15:26:19 runnervm48rkm libvirtd[7562]: Initialization of QEMU state driver failed: invalid argument: Failed to parse user 'libvirt-qemu'
Jun 12 15:26:19 runnervm48rkm libvirtd[7562]: Driver state initialization failed
Jun 12 15:26:19 runnervm48rkm systemd[1]: libvirtd.service: Deactivated successfully.