For Ubuntu 26.04 we have to be really explicit about the virsh connect target.
Addressing
  error: failed to get domain 'vm1.example.com'

  expect: spawn id exp3 not open
      while executing
  "expect_after timeout { puts "Waiting for login prompt timed out." ; exit 1 }"
      (file "/home/runner/work/virt-install-test/virt-install-test/.//util/virsh-console.expect" line 11)